### ISSUE TITLE
dataset-- images

### ISSUE THREAD

**Issue by zxy19961104** [zhuangbohan/HCVRD-a-benchmark-for-large-scale-Human-Centered-Visual-Relationship-Detection#1]
hi, how can i download the images dataset ?
http://visualgenome.org/api/v0/api_home.html  in this address ican  not download.

**Comment by bohanzhuang** [comment]
I checked and there's no problem to download the images at http://visualgenome.org/api/v0/api_home.html

**Comment by zxy19961104** [comment]
Thanks for your reply,i will try it again.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bohan Zhuang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 上午10:13
收件人:&nbsp;"zhuangbohan/HCVRD-a-benchmark-for-large-scale-Human-Centered-Visual-Relationship-Detection"<HCVRD-a-benchmark-for-large-scale-Human-Centered-Visual-Relationship-Detection@noreply.github.com&gt;;
抄送:&nbsp;"聆听者"<631133414@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhuangbohan/HCVRD-a-benchmark-for-large-scale-Human-Centered-Visual-Relationship-Detection] dataset-- images (#1)




I checked and there's no problem to download the images at http://visualgenome.org/api/v0/api_home.html
